---
production: &default
  serverPort: 9898
  baseUrl: http://www.instranet-seguros.com
  baseApi: /api/
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    minify: true
    stylusPrecompile: true
  controllers:
    default: home
  languages:
    default: en
    list: [en, es, fr, pt, jp]

stage: &stage
  <<: *default
  baseUrl: http://stage.intranet-seguros.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.intranet-seguros.com

development:
  <<: *latest
  baseUrl: http://local.intranet-seguros.com
  html:
    minify: false
    stylusPrecompile: false
